import React from 'react';

export const TermsPage: React.FC = () => {
    return (
        <div className="container" style={{ padding: '8rem 1rem 4rem', maxWidth: '800px', margin: '0 auto' }}>
            <h1 style={{ fontFamily: 'var(--font-serif)', fontSize: '2.5rem', marginBottom: '2rem' }}>
                Terms of Service
            </h1>

            <div style={{ color: 'var(--text-secondary)', lineHeight: 1.8, fontSize: '1rem' }}>
                <p style={{ marginBottom: '1.5rem' }}>
                    <strong>Last updated:</strong> {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
                </p>

                <h2 style={{ color: 'var(--text-primary)', fontSize: '1.5rem', marginTop: '2rem', marginBottom: '1rem' }}>
                    1. Acceptance of Terms
                </h2>
                <p style={{ marginBottom: '1.5rem' }}>
                    By accessing and using Joso, you accept and agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our service.
                </p>

                <h2 style={{ color: 'var(--text-primary)', fontSize: '1.5rem', marginTop: '2rem', marginBottom: '1rem' }}>
                    2. Description of Service
                </h2>
                <p style={{ marginBottom: '1.5rem' }}>
                    Joso is a natural language to JSON conversion tool. You provide text descriptions, and our service generates structured JSON output based on your input.
                </p>

                <h2 style={{ color: 'var(--text-primary)', fontSize: '1.5rem', marginTop: '2rem', marginBottom: '1rem' }}>
                    3. Acceptable Use
                </h2>
                <p style={{ marginBottom: '1rem' }}>You agree not to use Joso to:</p>
                <ul style={{ marginLeft: '1.5rem', marginBottom: '1.5rem' }}>
                    <li>Generate illegal, harmful, or malicious content</li>
                    <li>Attempt to reverse engineer or exploit the service</li>
                    <li>Overload or disrupt the service infrastructure</li>
                    <li>Violate any applicable laws or regulations</li>
                </ul>

                <h2 style={{ color: 'var(--text-primary)', fontSize: '1.5rem', marginTop: '2rem', marginBottom: '1rem' }}>
                    4. Intellectual Property
                </h2>
                <p style={{ marginBottom: '1.5rem' }}>
                    The JSON output generated by Joso based on your prompts belongs to you. The Joso brand, interface, and underlying technology remain our intellectual property.
                </p>

                <h2 style={{ color: 'var(--text-primary)', fontSize: '1.5rem', marginTop: '2rem', marginBottom: '1rem' }}>
                    5. Disclaimer of Warranties
                </h2>
                <p style={{ marginBottom: '1.5rem' }}>
                    Joso is provided "as is" without warranties of any kind. We do not guarantee that the generated JSON will be error-free or suitable for any particular purpose.
                </p>

                <h2 style={{ color: 'var(--text-primary)', fontSize: '1.5rem', marginTop: '2rem', marginBottom: '1rem' }}>
                    6. Limitation of Liability
                </h2>
                <p style={{ marginBottom: '1.5rem' }}>
                    We shall not be liable for any indirect, incidental, or consequential damages arising from your use of Joso.
                </p>

                <h2 style={{ color: 'var(--text-primary)', fontSize: '1.5rem', marginTop: '2rem', marginBottom: '1rem' }}>
                    7. Changes to Terms
                </h2>
                <p style={{ marginBottom: '1.5rem' }}>
                    We reserve the right to modify these terms at any time. Continued use of Joso after changes constitutes acceptance of the new terms.
                </p>
            </div>

            <a href="#" style={{
                display: 'inline-block',
                marginTop: '2rem',
                color: 'var(--accent-purple)',
                textDecoration: 'none',
                fontSize: '0.9rem'
            }}>
                ← Back to Home
            </a>
        </div>
    );
};
